### ISSUE TITLE
summarize this project in the README

### ISSUE THREAD

**Issue by ktdreyer** [release-engineering/cachito#171]
Here's a great summary that I found elsewhere:

Cachito is a service to store (and serve) source code for containers. Upon a request, cachito will fetch a specific revision of a given project from the web and store it in internal storage. Namely, it stores the source code for a specific git commit from a given git repository, which could be in a forge such as github or gitlab. This way, even if that repository (or that revision) gets deleted, it is still possible to track the pristine source code for the original sources.

Let's put this at the top of the README!

**Comment by lcarva** [comment]
Great idea! Submitted PR with a few modifications to the suggested text.
Thanks!
