### ISSUE TITLE
Include all of name, version and vcs url in purls in top-level packages

### ISSUE THREAD

**Issue by chmeliik** [release-engineering/cachito#420]
Purls are supposed to reflect where you can get the package. However, it is likely that our clients will be more interested in the type and declared name+version of the package, rather than the the git repository and commit ref.

Maybe we can have the best of both worlds if we just add the `vcs_url` qualifier to the `npm`, `pypi` and `golang` purls.

Examples (some normalization according to the [purl spec](https://github.com/package-url/purl-spec) may be needed):
- npm: `pkg:npm/cachito-npm-with-deps@1.0.0?vcs_url=https://github.com/cachito-testing/cachito-npm-with-deps@{ref}`
- pip: `pkg:pypi/cachito-pip-with-deps@1.0.0?vcs_url=https://github.com/cachito-testing/cachito-pip-with-deps@{ref}`
- golang, name matches repo: `pkg:golang/github.com/cachito-testing/cachito-gomod-with-deps@v0.0.0`
- golang, name does not match repo: `pkg:golang/k8s.io/kubernetes@v1.21.0?vcs_url=https://github.com/kubernetes/kubernetes@{ref}`

Some of the ideas here may also apply to dependencies, npm and pypi sometimes use generic or github purls.

**Comment by chmeliik** [comment]
@athos-ribeiro, any chance you could share an opinion on this? ^_^

**Comment by athos-ribeiro** [comment]
Hi Adam!

IIRC, I read a thread in the purl spec github issues (where they keep discussions related to purl) where one of the purl maintainers stated that ideally, we should keep PURLs as simple as possible (we just want to be able to locate/define a specific package).

For the image content manifests here, I suppose humans will not look at those often, instead, tools will (ideally, such tools developers would have an opinion on the matter).

Finally, if a package is available in the official NPM repository, saying `pkg:npm/another-package@1.0.0` should be enough for a tool to identify that an image needs attention. If, in the other hand, the component is only available through github, I fail to see how adding any information about the type or language of the package will aid any vulnerability scanners to perform their job. Again, it would be nice to bring the scanner developers into the discussion!

Sorry for the long time I took to reply to this one ;)
