### ISSUE TITLE
Set Content-Disposition: attachment with filename in /requests/{id}/download

### ISSUE THREAD

**Issue by lcarva** [release-engineering/cachito#86]
Set [Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) with a meaningful filename.

This would improve the user experience when users plug in the download url in the browser. The name should include the request ID and have `tar.gz` suffix.

**Comment by lcarva** [comment]
It looks like [flask.send_file](https://flask.palletsprojects.com/en/1.1.x/api/#flask.send_file) supports this.

**Comment by tkdchen** [comment]
This has been fixed in #124 and can be closed.
